include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    avoid_unnecessary_containers: true
    avoid_print: true
    always_use_package_imports: true
    unnecessary_null_checks: true
    avoid_unused_constructor_parameters: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    require_trailing_commas: true
    curly_braces_in_flow_control_structures: true
    unnecessary_nullable_for_final_variable_declarations: true
    null_check_on_nullable_type_parameter: true
    unnecessary_null_in_if_null_operators: true